[package]
name = "toy-kv"
version = "0.1.0"
authors = ["chux0519 <chuxdesign@hotmail.com>"]
edition = "2018"

[[example]]
name = "client"
path = "example/client.rs"

[[example]]
name = "server"
path = "example/server.rs"

[dependencies]
memmap = "0.7.0"
libc = "0.2"
